//! The `:help` key reference.

pub const TOPICS: &[(&str, &str)] = &[
    ("MOTIONS", ""),
    ("h j k l", "left, down, up, right"),
    (
        "w W b B e E",
        "word forward / back / end (capitals: to whitespace)",
    ),
    (
        "0 ^ $ g_",
        "line start, first non-blank, line end, last non-blank",
    ),
    ("gg G {n}G", "first line, last line, line n"),
    ("f F t T", "find character forward / back, till character"),
    ("; ,", "repeat / reverse the last f F t T"),
    ("{ }", "previous / next blank line"),
    ("%", "matching bracket"),
    ("H M L", "top, middle, bottom of the screen"),
    ("| {n}|", "column n"),
    (
        "m{a} `{a} '{a}",
        "set mark, jump to mark, jump to mark's line",
    ),
    ("Ctrl-O Ctrl-I", "older / newer position in the jump list"),
    ("", ""),
    ("SCROLLING", ""),
    ("Ctrl-D Ctrl-U", "half page down / up"),
    ("Ctrl-F Ctrl-B", "page down / up"),
    ("Ctrl-E Ctrl-Y", "one line down / up"),
    ("zz zt zb", "centre, top, bottom the cursor line"),
    ("", ""),
    ("EDITING", ""),
    (
        "i a I A",
        "insert before / after cursor, at first non-blank / line end",
    ),
    ("o O", "open a line below / above"),
    ("R", "replace mode"),
    ("x X", "delete character under / before the cursor"),
    ("s S", "substitute character / whole line"),
    ("D C Y", "delete / change to line end, yank line"),
    ("r{c}", "replace character with c"),
    ("~", "toggle case"),
    ("J", "join lines"),
    ("p P", "put after / before the cursor"),
    ("u Ctrl-R", "undo, redo"),
    (".", "repeat the last change"),
    ("", ""),
    ("OPERATORS", "combine with any motion or text object"),
    ("d c y", "delete, change, yank"),
    ("> <", "indent, dedent"),
    ("gu gU g~", "lowercase, uppercase, toggle case"),
    ("dd cc yy >>", "act on whole lines"),
    ("", ""),
    ("TEXT OBJECTS", "prefix with i (inner) or a (around)"),
    ("iw aw iW aW", "word"),
    ("i\" i' i`", "quoted string"),
    ("i( i[ i{ i<", "bracketed block"),
    ("ip ap", "paragraph"),
    ("", ""),
    ("VISUAL", ""),
    ("v V", "character-wise / line-wise selection"),
    ("o", "swap the ends of the selection"),
    ("d c y > < u U ~", "operate on the selection"),
    ("", ""),
    ("REGISTERS AND MACROS", ""),
    ("\"{a}", "use register a for the next delete, yank or put"),
    ("\"+y", "yank to the system clipboard (OSC 52)"),
    ("q{a} q @{a} @@", "record macro, stop, replay"),
    ("", ""),
    ("SEARCH", "patterns are Rust regular expressions"),
    ("/ ?", "search forward / backward"),
    ("n N", "next / previous match"),
    ("*", "search for the word under the cursor"),
    (":noh", "clear the search highlight"),
    ("", ""),
    ("COMMANDS", ""),
    (":w :w {file}", "write"),
    (":q :q!", "quit; quit discarding changes"),
    (":wq :x ZZ", "write and quit"),
    (":e {file} :e!", "edit a file, reload from disk"),
    (":ls :b {n} :bn :bp", "list buffers, switch, next, previous"),
    (":bd :bd!", "close the current buffer"),
    (":{n}", "go to line n"),
    (
        ":%s/from/to/g",
        "substitute (\\1 refers to a capture group)",
    ),
    (
        ":set nu :set ts=2",
        "change an option; :set opt? to query it",
    ),
    (":reg :marks", "list registers, marks"),
    (":help", "this list"),
    ("", ""),
    ("SHARED SESSIONS", ""),
    (
        ":share",
        "start hosting this editor; prints a URL and an attach command",
    ),
    (
        ":share --write",
        "...with guests able to edit straight away",
    ),
    (
        ":share --port N",
        "...on a fixed port, for a stable SSH tunnel",
    ),
    (
        ":who",
        "participants, where they are, and how they connected",
    ),
    (":grant {name}", "let a guest edit"),
    (":revoke {name}", "put a guest back to read-only"),
    (":follow {name}", "mirror another participant's viewport"),
    (":unfollow", "go back to your own viewport"),
    (":say {text}", "send a line to everyone in the session"),
    (":unshare", "end the session"),
    (
        "miv --attach",
        "join a session from another terminal (Ctrl-\\ detaches)",
    ),
];
